apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/2 * * * *"  #cronjob-schedule
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: back-up-service
            image: suyog23/back-up-service
            imagePullPolicy: IfNotPresent  # Or appropriate policy
          imagePullSecrets:
          - name: my-registry-secret
          restartPolicy: OnFailure
